[pytest]
markers =
    auth: на регистрацию
    positive: позитивные тесты
    negative: негативные тесты
    positive_auth: позитивные тесты на авторизацию
    negative_auth: негативные тесты на авторизацию